---
title: "R Notebook"
output: html_notebook
author: "Ryan Willett"
---


```{r}
library(ggplot2)
library(tidyverse)
library(feather)
```

```{r}
all_countries_seg <- read_feather("parsed_data/regional_confirmed.feather")
all_countries_seg_deaths <- read_feather("parsed_data/regional_deaths.feather")

rolling_cases <- read_feather("parsed_data/rolling_cases_country.feather")
rolling_deaths <- read_feather("parsed_data/rolling_deaths_country.feather")

rolling_cases_states <- read_feather("parsed_data/states_cases_rolling.feather")
rolling_deaths_states <- read_feather("parsed_data/states_deaths_rolling.feather")

```


```{r}
#NEW CASES
asia_newcases <- rolling_cases %>% filter(Region=='Asia' | Region=="Middle East")
europe_newcases <- rolling_cases %>% filter(Region=='Europe')
west_newcases <- rolling_cases %>% filter(Region=='North America' | Region=="South America")

#NEW DEATHS
asia_newdeaths <- rolling_deaths %>% filter(Region=='Asia' | Region=="Middle East")
europe_newdeaths <- rolling_deaths %>% filter(Region=='Europe')
west_newdeaths <- rolling_deaths %>% filter(Region=='North America' | Region=="South America")

```

```{r}
sw_states <- c("Arizona", "New Mexico", "Nevada", "Utah")
carolinas <- c("North Carolina", "South Carolina")
```

```{r}
sw_data <- rolling_cases_states %>% filter(state %in% sw_states)
carolinas_data <- rolling_cases_states %>% filter(state %in% carolinas)
```

```{r}
sw_data2 <- sw_data %>% filter(date > as.POSIXct("2020-03-01", "%Y-%m-%d"))
sw_data2
```


```{r}

man_col <- scale_color_manual(values = c("red", "darkgreen", "orange", "blue"))

ggplot(sw_data2, aes(x=date, y=new_cases_pop100k, col=state)) + 
  geom_line(size=0.75) + 
  theme_classic(base_size = 16) + man_col +
  labs(x="", y="New Cases Per 100k People", caption="7 Day Rolling Average\nVertical lines indicate end of stay-at-home orders (SAHO)", col="State") + 
  geom_vline(xintercept = as.POSIXct(strptime("2020-05-15", "%Y-%m-%d")), color="red", size=0.75, linetype='dotdash') + # End of AZ SAH orders
  geom_vline(xintercept = as.POSIXct(strptime("2020-05-31", "%Y-%m-%d")), color="orange", size=0.75, linetype='dotted') + # End of NM SAH orders
  geom_vline(xintercept = as.POSIXct(strptime("2020-05-09", "%Y-%m-%d")), color="darkgreen", size=0.75, linetype='twodash') + # End of NV SAH orders
  geom_vline(xintercept = as.POSIXct(strptime("2020-05-15", "%Y-%m-%d")), color="blue", size=0.75, linetype='dotted') + # End of UT SAH orders
  annotate(geom = "text", x = as.POSIXct(strptime("2020-05-07", "%Y-%m-%d")), y = 15, label = "End of NV SAHO", color = "darkgreen",
             angle = 90) + 
  annotate(geom = "text", x = as.POSIXct(strptime("2020-05-13", "%Y-%m-%d")), y = 15, label = "End of UT SAHO", color = "blue",
             angle = 90) + 
  annotate(geom = "text", x = as.POSIXct(strptime("2020-05-17", "%Y-%m-%d")), y = 15, label = "End of AZ SAHO", color = "red",
             angle = 90) + 
  annotate(geom = "text", x = as.POSIXct(strptime("2020-05-29", "%Y-%m-%d")), y = 15, label = "End of NM SAHO", color = "orange",
             angle = 90)
  # scale_x_datetime(limits = ymd_h(c("2020-03-13 00", "2020-04-20 23"))) +
```

```{r}
cny_extended <- all_countries_seg %>% filter(Date >= as.POSIXct("2020-01-25", format="%Y-%m-%d")) %>% 
  filter(Date < as.POSIXct("2020-02-14", format="%Y-%m-%d")) %>% 
  filter(Confirmed > 0) %>% 
  pull(Country) %>% 
  unique() %>% 
  sort()

cny_extended
```

```{r}
cny <- all_countries_seg %>% filter(Date >= as.POSIXct("2020-01-25", format="%Y-%m-%d")) %>% 
  filter(Date < as.POSIXct("2020-01-31", format="%Y-%m-%d")) %>% 
  filter(Confirmed > 0) %>% 
  pull(Country) %>% 
  unique() %>% 
  sort()

cny
```

```{r}
before_cny <- all_countries_seg %>% filter(Date < as.POSIXct("2020-01-25", format="%Y-%m-%d")) %>% 
  # filter(Date < as.POSIXct("2020-02-14", format="%Y-%m-%d")) %>% 
  filter(Confirmed > 0) %>% 
  pull(Country) %>% 
  unique()

before_cny
```

Countries with first cases appearing during the full span of the official and extended CNY holiday
```{r}
countries_fcases_cny_extended <- setdiff(cny_extended, before_cny)
countries_fcases_cny_extended
```

Countries with first cases appearing during the official CNY holiday
```{r}
countries_fcases_cny <- setdiff(cny, before_cny)
countries_fcases_cny
```

Countries with first cases appearing during the extended CNY holiday
```{r}
countries_fcases_extended <- setdiff(countries_fcases_cny_extended, countries_fcases_cny)
countries_fcases_extended
```

```{r}
before_data <- rolling_cases %>% filter(Country %in% before_cny)
cny_data <- rolling_cases %>% filter(Country %in% countries_fcases_cny)
extended_data <- rolling_cases %>% filter(Country %in% countries_fcases_cny_extended)
onlyextended_data <- rolling_cases %>% filter(Country %in% countries_fcases_extended)
```

```{r}
include_from_before <- c("US", "France", "Japan", "Korea, South", "Singapore", "Nepal")
before_data <- before_data %>% filter(Country %in% include_from_before)
```


```{r}
ggplot(before_data, aes(x=Date, y=new_confirmed100k, col=Country)) + 
  geom_line(size=0.75) + 
  theme_classic(base_size = 16) + 
  labs(x="", y="New Cases Per 100k People", caption="7 Day Rolling Average", col="Country") +
  geom_rect(
    fill = "yellow", alpha = 0.01,
    xmin = as.POSIXct(strptime("2020-01-25", "%Y-%m-%d")),
    xmax = as.POSIXct(strptime("2020-01-31", "%Y-%m-%d")),
    ymin = 0,
    ymax = Inf, 
    col="black"
  ) +
  geom_rect(
    fill = "orange", alpha = 0.01,
    xmin = as.POSIXct(strptime("2020-01-31", "%Y-%m-%d")),
    xmax = as.POSIXct(strptime("2020-02-14", "%Y-%m-%d")),
    ymin = 0,
    ymax = Inf, 
    col="black"
  )
```

```{r}
cny_data$Country %>% unique()
```


```{r}
east_asia <- c("Cambodia", "Philippines")
south_asia <- c("India", "Sri Lanka")
europe <- c("Finland", "Germany", "Italy", "Russia", "Sweden", "United Kingdom")
namerica <- c("Canada", "United States")
middleeast <- c("United Arab Emirates")
```


```{r}
ggplot(cny_data, aes(x=Date, y=new_confirmed100k, col=Country)) + 
  geom_line(size=0.75) + 
  theme_classic(base_size = 16) + 
  labs(x="", y="New Cases Per 100k People", caption="7 Day Rolling Average", col="Country") +
  geom_rect(
    fill = "yellow", alpha = 0.01,
    xmin = as.POSIXct(strptime("2020-01-25", "%Y-%m-%d")),
    xmax = as.POSIXct(strptime("2020-01-31", "%Y-%m-%d")),
    ymin = 0,
    ymax = Inf, 
    col="black"
  ) +
  geom_rect(
    fill = "orange", alpha = 0.01,
    xmin = as.POSIXct(strptime("2020-01-31", "%Y-%m-%d")),
    xmax = as.POSIXct(strptime("2020-02-14", "%Y-%m-%d")),
    ymin = 0,
    ymax = Inf, 
    col="black"
  )
```

```{r}
ggplot(extended_data, aes(x=Date, y=new_confirmed100k, col=Country)) + 
  geom_line(size=0.75) + 
  theme_classic(base_size = 16) + 
  labs(x="", y="New Cases Per 100k People", caption="7 Day Rolling Average", col="Country") +
  geom_rect(
    fill = "yellow", alpha = 0.01,
    xmin = as.POSIXct(strptime("2020-01-25", "%Y-%m-%d")),
    xmax = as.POSIXct(strptime("2020-01-31", "%Y-%m-%d")),
    ymin = 0,
    ymax = Inf, 
    col="black"
  ) +
  geom_rect(
    fill = "orange", alpha = 0.01,
    xmin = as.POSIXct(strptime("2020-01-31", "%Y-%m-%d")),
    xmax = as.POSIXct(strptime("2020-02-14", "%Y-%m-%d")),
    ymin = 0,
    ymax = Inf, 
    col="black"
  )
```

```{r}
ggplot(onlyextended_data, aes(x=Date, y=new_confirmed100k, col=Country)) + 
  geom_line(size=0.75) + 
  theme_classic(base_size = 16) + 
  labs(x="", y="New Cases Per 100k People", caption="7 Day Rolling Average", col="Country") +
  geom_rect(
    fill = "yellow", alpha = 0.01,
    xmin = as.POSIXct(strptime("2020-01-25", "%Y-%m-%d")),
    xmax = as.POSIXct(strptime("2020-01-31", "%Y-%m-%d")),
    ymin = 0,
    ymax = Inf, 
    col="black"
  ) +
  geom_rect(
    fill = "orange", alpha = 0.01,
    xmin = as.POSIXct(strptime("2020-01-31", "%Y-%m-%d")),
    xmax = as.POSIXct(strptime("2020-02-14", "%Y-%m-%d")),
    ymin = 0,
    ymax = Inf, 
    col="black"
  )
```