---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggplot2)
library(feather)
library(lubridate)

library(mapdeck)
library(colourvalues)
library(sf)
library(tidyverse)
library(ggplot2)
library(googleVis)
library(colourvalues)
library(jsonify)
library(geojsonsf)
library(spatialwidget)
library(googlePolylines)
library(readr)
library(scales)

setwd("~/CRA/COVID-19")
```


```{r}
all_countries_agg <- read_feather("parsed_data/all_countries_summary.feather")

# state_data_new = read_feather("data/us_states_newcases.feather")

us_atlantic <- read_feather("parsed_data/us_data_atlantic.feather")

state_atlantic <- read_feather("parsed_data/states_data_atlantic.feather")
```

```{r}
ggplot(all_countries_agg, aes(x=Date, y=Confirmed)) + 
      geom_col() + 
      theme_classic(base_size = 16) +
      labs(x="", y="Cases", title="Global Cases by Day from Jan 22, 2020") + 
      geom_hline(yintercept = 1000000, linetype="dashed", color="red") + 
      annotate(geom="text", x=as.POSIXct(strptime("2020-02-10", "%Y-%m-%d")), y=1150000, label="1 million cases", color="red") +
      geom_hline(yintercept = 2000000, linetype="dashed", color="red") + 
      annotate(geom="text", x=as.POSIXct(strptime("2020-02-10", "%Y-%m-%d")), y=2150000, label="2 million cases", color="red") +
      geom_hline(yintercept = 3000000, linetype="dashed", color="red") + 
      annotate(geom="text", x=as.POSIXct(strptime("2020-02-10", "%Y-%m-%d")), y=3150000, label="3 million cases", color="red") +
      geom_hline(yintercept = 4000000, linetype="dashed", color="red") + 
      annotate(geom="text", x=as.POSIXct(strptime("2020-02-10", "%Y-%m-%d")), y=4150000, label="4 million cases", color="red") +
      geom_hline(yintercept = 5000000, linetype="dashed", color="red") + 
      annotate(geom="text", x=as.POSIXct(strptime("2020-02-10", "%Y-%m-%d")), y=5150000, label="5 million cases", color="red") +
      scale_y_continuous(labels = scales::comma) + 
      theme(plot.title = element_text(hjust = 0.5))

ggsave("global_cases.png", width=8, height=6)
```



```{r}
normalized_covid <- state_data_new %>% 
  filter(date == max(date)) %>% 
  dplyr::select(state, abbrev, cases_pop100k, deaths_pop100k, new_cases_pop100k, new_deaths_pop100k)

normalized_covid
```

```{r}
normalized_covid <- state_data_new %>% 
  filter(date == max(date)) %>% 
  dplyr::select(state, abbrev, cases_pop100k, deaths_pop100k, new_cases_pop100k, new_deaths_pop100k)

normalized_covid
```

```{r}
all_data <- merge(normalized_covid, recent_testing, by.x="abbrev",  by.y="state")
all_data
```

```{r}
ggplot(all_data, aes(x=totTestNorm_100k, y=cases_pop100k, label=state)) + 
  geom_point(color = "") + 
  geom_text_repel() + 
  labs(x="Tests Per 100,000 People", y="COVID-19 Cases Per 100,000 People") + 
  theme_classic()
```



```{r}
# us_hosp <- us_atlantic %>% 
#   dplyr::select(date, hospitalizedCumulative, inIcuCumulative, onVentilatorCumulative) %>% 
#   gather("outcome", "value", 2:4)
# us_hosp
```

```{r}
# us_hosp_current <- us_atlantic %>% 
#   dplyr::select(date, hospitalizedCurrently, inIcuCurrently, onVentilatorCurrently) %>% 
#   gather("outcome", "value", 2:4)
# us_hosp_current %>% mutate(label = case_when(
#   outcome == "hospitalizedCurrently" ~ "Hospitalized Currently", 
#   outcome == "inIcuCurrently" ~ "In ICU Currently", 
#   outcome == "onVentilatorCurrently" ~ "On Ventilator Currently"
# ))
```





```{r}
us_test <- us_atlantic %>% dplyr::select(date, total, positive, negative) %>% 
  gather("result", "value", 2:4)
us_test
```

```{r}
us_test_rate <- us_atlantic %>% dplyr::select(date, totalTestResultsIncrease, positiveIncrease, negativeIncrease) %>% 
  gather("result", "value", 2:4)
us_test_rate
```


```{r}
dataplot_test <- us_test_rate %>% drop_na() %>% filter(result=="totalTestResultsIncrease")

dataplot_test
```


```{r}
ggplot(dataplot_test, aes(x=date, y=value, col=result)) + 
  geom_line(show.legend = F, color="black") +
  theme_classic(base_size = 16) + 
  geom_hline(yintercept = 900000, linetype="dashed", color="red") + 
  annotate(geom="text", x=as.POSIXct(strptime("2020-03-10", "%Y-%m-%d")), y=920000, label="'Bare Minimum Scenario': 900,000 tests per day", color="red") +
  scale_y_continuous(labels = scales::comma) + 
  labs(x = "", y = "US Testing Capacity (Tests/Day)", title="Testing Falls Short of Reopening Requirements") + 
  theme(plot.title = element_text(hjust = 0.5))

ggsave("total_testing_us.png", width=8, height=4)

# ggplot(dataplot_test, aes(x=date, y=value, col=result)) + 
#   geom_line(show.legend = F, color="black") +
#   theme_classic() + 
#   geom_hline(yintercept = 900000, linetype="dashed", color="red") + 
#   annotate(geom="text", x=as.POSIXct(strptime("2020-03-10", "%Y-%m-%d")), y=1010000, label="'Bare Minimum Scenario': 900,000 tests per day", color="red") +
#   geom_hline(yintercept = 5000000, linetype="dashed", color="red") +
#   annotate(geom="text", x=as.POSIXct(strptime("2020-03-10", "%Y-%m-%d")), y=5110000, label="900,000 tests per day", color="red") +
#   scale_y_continuous(labels = scales::comma) + 
#   labs(x = "", y = "Testing Capacity (Tests/Day)")
# 
# ggplot(dataplot_test, aes(x=date, y=value, col=result)) + 
#   geom_line(show.legend = F, color="black") +
#   theme_classic() + 
#   geom_hline(yintercept = 900000, linetype="dashed", color="red") + 
#   annotate(geom="text", x=as.POSIXct(strptime("2020-03-10", "%Y-%m-%d")), y=2000000, label="'Bare Minimum Scenario': 900,000 tests per day", color="red") +
#   geom_hline(yintercept = 5000000, linetype="dashed", color="red") +
#   annotate(geom="text", x=as.POSIXct(strptime("2020-03-10", "%Y-%m-%d")), y=6000000, label="'Moderate Scenario': 5 million tests per day", color="red") +
#   geom_hline(yintercept = 35000000, linetype="dashed", color="red") +
#   annotate(geom="text", x=as.POSIXct(strptime("2020-03-10", "%Y-%m-%d")), y=36000000, label="'Aggressive Scenario': 35 million tests per day", color="red") +
#   scale_y_continuous(labels = scales::comma) + 
#   labs(x = "", y = "Testing Capacity (Tests/Day)")
```