---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggplot2)
library(feather)
library(ggrepel)
```



```{r}
state_data = read_feather("data/us_states.feather")
state_data_new = read_feather("data/us_states_newcases.feather")
atlantic = read_feather("data/states_data_atlantic.feather")
```

```{r}
recent_testing <- atlantic %>% filter(date == max(date)) # Filtering most recent date
recent_testing <- recent_testing %>% dplyr::select(name, state, totalTestResults, pop_2019) %>% mutate(totTestNorm_100k = totalTestResults/pop_2019*100000)
recent_testing <- recent_testing[!duplicated(recent_testing),] # Removing duplicated Puerto Rico records

```



```{r}
recent_testing %>% arrange(desc(totTestNorm_100k)) %>% head(10)
```


```{r}
normalized_covid <- state_data_new %>% 
  filter(date == max(date)) %>% 
  dplyr::select(state, abbrev, cases_pop100k, deaths_pop100k, new_cases_pop100k, new_deaths_pop100k)

normalized_covid
```

```{r}
all_data <- merge(normalized_covid, recent_testing, by.x="abbrev",  by.y="state")
all_data
```





```{r}
ggplot(all_data, aes(x=totTestNorm_100k, y=cases_pop100k, label=state)) + 
  geom_point() + 
  # geom_smooth() +
  # geom_text_repel() + 
  labs(x="Tests Per 100,000 People", y="COVID-19 Cases Per 100,000 People") + 
  theme_classic()
```

```{r}
ggplot(all_data, aes(x=totTestNorm_100k, y=cases_pop100k, label=state)) + 
  geom_point(color = "red") + 
  geom_text_repel() + 
  labs(x="Tests Per 100,000 People", y="COVID-19 Cases Per 100,000 People", title="Detection Is Correlated with Testing", caption="Cypress River Advisors LLC ©, 2020") + 
  theme_classic(base_size = 16) + 
  theme(plot.title = element_text(hjust = 0.5))

ggsave("cases_v_test_normalized.png", width=8, height=6)
```

```{r}
ggplot(all_data, aes(x=totTestNorm_100k, y=cases_pop100k, label=state)) + 
  geom_point(color = "red") + 
  geom_text_repel() + 
  labs(x="Tests Per 100,000 People", y="COVID-19 Cases Per 100,000 People", title="Detection Is Correlated with Testing", caption="Cypress River Advisors LLC ©, 2020") + 
  theme_classic(base_size = 18) + 
  theme(plot.title = element_text(hjust = 0.5))

ggsave("cases_v_test_normalized_big.png", width=16, height=12)
```